### PR TITLE
Refactor to Lerna, react-scripts, eslint-config-kununu

### PR DESCRIPTION
**Pull request by karlhorky**

### CODE REVIEW

**Comment by feychou** [comment]
This is really cool!

Can we rename the header to KununuHeader? It seems like PascalCase is the standard for names of components' directories.

**Comment by karlhorky** [comment]
Ah, I was just following the Lerna standard of naming it the same as the npm package name.

But if it's important for us, we can rename it!

**Comment by feychou** [comment]
Hah, that is true, they are gonna be packages too. So I guess we should keep them this way after all.

**Comment by karlhorky** [comment]
Cool, sounds good.

**Comment by karlhorky** [comment]
Just fixing the errors with the playground now

**Comment by karlhorky** [comment]
Got dependencies working! We're using `react-scripts` now for a lot of the boilerplate deps.

**Comment by karlhorky** [comment]
Oh man, just found another really cool thing about Lerna. Apparently when you run `bootstrap` [it links together local dependencies that depend on each other](https://github.com/lerna/lerna/blob/b35c05fc5a4a77e97560e1af639ca7f3db79c569/README.md#what-can-lerna-do)!

This means that when we depend on `kununu-logo` within `kununu-header`, `lerna bootstrap` actually just symlinks to the other package. Awesome!

cc @feychou @kaytcat @clopes-ventureoak @FreaKzero

**Comment by feychou** [comment]
@karlhorky I noticed the sass-lint file still has this rule for 

`include: 'components/**/*.scss'`

Since we do not have the components folder anymore, this is probably invalid now.
Should this file be in the root folder too?

**Comment by karlhorky** [comment]
Nice catch! Fixed!

**Pull request merged**
